#!/usr/bin/env bash

# PUBLIC VARIABLES AND FUNCTIONS
# ==============================

# The root directory where all contexts (represent by subdirectories) are kept.
CTX_ROOT="${HOME}/.bash-ctx"

# Context management. Call `ctx help` for details.
ctx() {
    local command="$1"

    shift

    case "${command}" in
        "new") _ctx_new $@ ;;
        "delete") _ctx_delete $@ ;;
        "enter") _ctx_enter $@ ;;
        "leave") _ctx_leave $@ ;;
        "edit") _ctx_edit $@ ;;
        "reload") _ctx_reload $@ ;;
        "list") _ctx_list $@ ;;
        "help") _ctx_help ;;
        "") _ctx_help ;;
        *) _ctx_unknown "${command}" ;;
    esac
}

# SUBCOMMANDS
# ===========

# Usage: _ctx_new <context name>
# Create a new context or report an _error if it does not exist.
_ctx_new() {
    local ctx_dir="${CTX_ROOT}/$1"

    if [ -e "${ctx_dir}" ]; then
        _error "the context $1 already exist"
        return
    fi

    mkdir -p "${ctx_dir}"
    touch "${ctx_dir}/enter"
    touch "${ctx_dir}/leave"
    _success "created context $1"
}

# Usage: _ctx_delete <context name>
# Delete an existing context.
_ctx_delete() {
    if [ "${CTX_NAME}" == "$1" ]; then
        _error "leave the current context before deleting it"
    fi

    local ctx_dir="${CTX_ROOT}/$1"

    if [ ! -e "${ctx_dir}" ]; then
        _error "the context $1 does not exist"
        return
    fi

    rm -rf "${ctx_dir}"
}

# Usage: _ctx_enter <context name>
# Enter the specified context: call its enter script (if it exists) and restore
# history. Reports an _error if the context does not exist or if already in
# another context. Does nothing when called with the current context.
_ctx_enter() {
    if [ "${CTX_NAME}" == "$1" ]; then
        return
    fi

    if [ -n "${CTX_NAME}" ]; then
        _error "leave the current context ${CTX_NAME} first"
        return 1
    fi

    local ctx_dir="${CTX_ROOT}/$1"
    local histfile=""

    if [ ! -e "${ctx_dir}" ]; then
        _error "the context $1 does not exist"
        return 1
    fi

    _try_source "${ctx_dir}/enter"

    export HISTFILE="${ctx_dir}/history"
    history -r

    export CTX_NAME="$1"
}

# Usage: _ctx_leave
# Leave the current context: save the context-specifc command history and call
# the leave script (if it exist). Does nothing if callout outside of a context.
_ctx_leave() {
    if [ -z "${CTX_NAME}" ]; then
        return
    fi

    history -a

    local ctx_dir="${CTX_ROOT}/${CTX_NAME}"
    _try_source "${ctx_dir}/leave"
    unset CTX_NAME
}

# Usage: _ctx_list
# List existing contexts.
_ctx_list() {
    command ls "${CTX_ROOT}"
}

# Usage: _ctx_edit <file name>
# Edit a context-related file.
_ctx_edit() {
    if [ -z "${CTX_NAME}" ]; then
        _error "enter a context first"
        return 1
    fi
    if [ -z "${EDITOR}" ]; then
        _error "set EDITOR to the editor of your choice"
        return 1
    fi

    local ctx_dir="${CTX_ROOT}/${CTX_NAME}"
    local path="${ctx_dir}/$1"

    "$EDITOR" "${path}"
}

# Usage: _ctx_reload
# Reload the current context
_ctx_reload() {
    if [ -z "${CTX_NAME}" ]; then
        _error "no context to reload"
        return 1
    fi

    local ctx_name="$CTX_NAME"

    _ctx_leave
    _ctx_enter "$ctx_name"
}

# Usage: _ctx_help
# Display a help for the commend.
_ctx_help() {
    echo "Usage:"
    echo "  ctx <command> <command arguments>"
    echo
    echo "Commands:"
    echo "  new <context name>      create a new context"
    echo "  delete <context name>   delete an existing context"
    echo "  enter <context name>    enter a context"
    echo "  edit <file name>        edit a context-related file"
    echo "  leave                   leave the current context"
    echo "  list                    list all existing contexts"
    echo "  help                    display this message"
}

# Usage: _ctx_unknown <command name>
# Report an _error about an unknown command.
_ctx_unknown() {
    _error "unknown command $1"
    _ctx_help
    return 1
}

# INTERNALS
# =========

# Color sequences.
_CTX_RED="$(tput setaf 1)"
_CTX_GREEN="$(tput setaf 2)"
_CTX_RESET="$(tput sgr0)"

# Usage: _try_source <path to a bash script>
# Load the specified bash script if it exists; do nothing otherwise.
_try_source() {
    if [ -r "$1" ]; then
        source "$1"
    fi
}

# Usage: _error <message>
# Dispaly an error message.
_error() {
    echo "${_CTX_RED}Error: $1${_CTX_RESET}"
}

# Usage: _success <message>
# Display a success message.
_success() {
    echo "${_CTX_GREEN}Success: $1${_CTX_RESET}"
}

# COMMAND COMPLETION
# ==================

# Command line completion function.
_ctx_complete() {
    local options=''

    case "${COMP_WORDS[COMP_CWORD - 1]}" in
        ctx) options='new delete enter leave reload edit list help' ;;
        delete) options=$(ls -1 ${CTX_ROOT}) ;;
        enter) options=$(ls -1 ${CTX_ROOT}) ;;
        edit) options=$(ls -1 "${CTX_ROOT}/${CTX_NAME}") ;;
    esac

    COMPREPLY=($(compgen -W "${options}" ${COMP_WORDS[COMP_CWORD]}))
}

# Complete ctx.
complete -F _ctx_complete ctx

# Call `ctx leave` when quitting the shell.
trap _ctx_leave EXIT

# SUPPORTING FILES AND DIRECTORIES
# ================================

# Usage: _setup
# Setup supporting files and directories if they don't exist. Enter the context
# specified by CTX_NAME.
_setup() {
    if [[ ! -d "${CTX_ROOT}" ]]; then
        mkdir -p "${CTX_ROOT}"
    fi

    if [ "${PS1+x}" = "x" -a "${-#*i}" != "$-" -a -n "${CTX_NAME}" ]; then
        CTX_NAME_COPY="${CTX_NAME}"
        CTX_NAME=""
        _ctx_enter "${CTX_NAME_COPY}"
    fi
}

_setup
