#!/usr/bin/env bash
sudo bash -c "curl -fsSL https://raw.githubusercontent.com/grn/bash-ctx/master/bash-ctx > /usr/libexec/bash-ctx"
echo "[ -r /usr/libexec/bash-ctx ] && source /usr/libexec/bash-ctx" >> "${HOME}/.bashrc"