#!/usr/bin/env bash

set -e

mkdir -p "${HOME}/.bash-ctx"
cp bash-ctx "${HOME}/.bash-ctx.source"

echo
echo 'Please remember to add the following to your .bashrc:'
echo
echo 'if [ -r "${HOME}/.bash-ctx.source" ]; then'
echo '    source "${HOME}/.bash-ctx.source"'
echo 'fi'
