#!/usr/bin/env bash

set -e

TARGET="${HOME}/.bash-ctx"

mkdir -p "${TARGET}"
cp bash-ctx "${TARGET}"
cp -r lib "${TARGET}"

echo
echo 'Please remember to add the following to your .bashrc:'
echo
echo 'if [ -r "${HOME}/.bash-ctx/bash-ctx" ]; then'
echo '    source "${HOME}/.bash-ctx/bash-ctx"'
echo 'fi'
